<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="V2.Tests/**/*.cs" />
    <None Include="V2.Tests/**/*.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Backend\DonghanEngine.Core\DonghanEngine.Core.csproj" />
  </ItemGroup>
</Project>
