using System.Collections.Generic;

namespace DonghanEngine.Core;

public static class HistoricalNpcPresets
{
    public static List<NpcState> All { get; } = new()
    {
        // 洛阳朝堂 / 开局可见
        N("yuan_shao", "袁绍", "中军校尉", 2, 154, 48, "清流派", 42, 35, 25, 800, 55, 68, 62, 86, 86,
            new() { TraitNames.MenFaShiJia, TraitNames.ChuShenMingMen, TraitNames.ShouXiaYouBing, TraitNames.LaoMouShenSuan }, "外宽内忌", "结党营私", "洛阳朝堂", "开局", "四世三公袁氏子弟，西园军与门阀清流代表"),
        N("yuan_shu", "袁术", "虎贲中郎将", 2, 155, 44, "清流派", 35, 30, 55, 1200, 45, 52, 45, 60, 92,
            new() { TraitNames.MenFaShiJia, TraitNames.ChuShenMingMen, TraitNames.HaoSheWuDu, TraitNames.TanDeWuYan }, "骄矜", "结党营私", "洛阳朝堂", "开局", "袁氏嫡支权贵，未来淮南割据与僭号风险源"),
        N("wang_yun", "王允", "尚书令", 3, 137, 55, "清流派", 48, 40, 8, 120, 20, 45, 82, 72, 58,
            new() { TraitNames.GangZhiBuE, TraitNames.JingTianWeiDi, TraitNames.LaoMouShenSuan, TraitNames.QingZhengLianJie }, "刚峻", "雷厉风行", "洛阳朝堂", "开局", "清流重臣，后主持诛董"),
        N("lu_zhi", "卢植", "北中郎将", 3, 130, 62, "清流派", 55, 28, 3, 80, 55, 82, 80, 76, 18,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.ShanChangMinZheng, TraitNames.GangZhiBuE, TraitNames.QingZhengLianJie }, "刚正", "直言守礼", "洛阳朝堂", "开局", "经学名儒与黄巾前线统帅，刘备师长；生年不详，按老成名宿估算"),
        N("huangfu_song", "皇甫嵩", "左中郎将", 3, 130, 65, "清流派", 60, 32, 10, 200, 76, 93, 56, 72, 22,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.AiBingRuZi, TraitNames.GangZhiBuE, TraitNames.DongDianBingFa }, "忠勇", "雷厉风行", "洛阳朝堂", "开局", "平定黄巾的帝国军方王牌"),
        N("zhu_jun", "朱儁", "右中郎将", 3, 135, 60, "清流派", 56, 26, 12, 180, 72, 86, 58, 66, 28,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.DongDianBingFa, TraitNames.TiXuShiZu }, "沉毅", "务实平乱", "洛阳朝堂", "开局", "平黄巾名将，南方与豫荆方向军政经验充足"),
        N("zhao_zhong", "赵忠", "中常侍", 3, 135, 55, "阉党派", 72, 68, 88, 5200, 8, 12, 58, 62, 82,
            new() { TraitNames.TanDeWuYan, TraitNames.ChanMeiZhuanQuan, TraitNames.HuiPaiMaPi }, "谄媚阴狠", "谄媚专权", "洛阳宫中", "开局", "十常侍核心，灵帝宠宦"),
        N("duan_gui", "段珪", "中常侍", 2, 140, 50, "阉党派", 66, 45, 78, 2600, 10, 12, 45, 48, 72,
            new() { TraitNames.TanDeWuYan, TraitNames.HuiPaiMaPi, TraitNames.YouXieXinJi }, "机警", "结党护短", "洛阳宫中", "开局", "十常侍成员，宫变节点人物"),
        N("bi_lan", "毕岚", "中常侍", 2, 142, 47, "阉党派", 70, 38, 82, 1800, 5, 10, 42, 55, 65,
            new() { TraitNames.PuZhangLangFei, TraitNames.TanDeWuYan, TraitNames.ChanMeiZhuanQuan }, "巧佞", "宫室营造", "洛阳宫中", "开局", "灵帝宠宦，宫室工程与内廷耗费代表"),
        N("he_miao", "何苗", "车骑将军", 3, 140, 49, "外戚派", 38, 50, 52, 1100, 42, 40, 35, 38, 66,
            new() { TraitNames.ShouXiaYouBing, TraitNames.YouXieShouZang, TraitNames.ChuShenMingMen }, "依附权势", "外戚分权", "洛阳朝堂", "开局", "本朱氏子，又名朱苗；与何进、何皇后同属外戚集团，史料关系表述有歧"),
        N("yang_biao", "杨彪", "侍中", 3, 142, 83, "清流派", 50, 38, 18, 600, 15, 35, 78, 75, 35,
            new() { TraitNames.MenFaShiJia, TraitNames.ChuShenMingMen, TraitNames.ShanChangMinZheng }, "持重", "守礼周旋", "洛阳朝堂", "开局", "弘农杨氏名臣，汉室旧臣与门阀清议代表"),
        N("ma_ridi", "马日磾", "谏议大夫", 3, 140, 54, "清流派", 54, 32, 6, 150, 8, 20, 76, 72, 20,
            new() { TraitNames.QingZhengLianJie, TraitNames.ShanChangMinZheng, TraitNames.QinMinWenHe }, "温厚守礼", "礼法调停", "洛阳朝堂", "开局", "经学名臣，礼法与朝廷名义象征"),
        N("cai_yong", "蔡邕", "议郎", 1, 132, 60, "清流派", 45, 18, 2, 60, 5, 15, 62, 82, 12,
            new() { TraitNames.QingZhengLianJie, TraitNames.XiHaoQingTan, TraitNames.QinMinWenHe }, "文雅直敏", "清议文名", "洛阳朝堂", "开局", "文学经学名士，蔡文姬之父，士人舆论代表"),
        N("yuan_wei", "袁隗", "太傅", 4, 130, 60, "清流派", 44, 62, 35, 2200, 18, 35, 78, 74, 70,
            new() { TraitNames.MenFaShiJia, TraitNames.ChuShenMingMen, TraitNames.LaoMouShenSuan }, "圆滑持重", "门阀调停", "洛阳朝堂", "开局", "袁氏宗族长辈，朝中门生故吏极广，能稳清议也会庇护袁氏私势"),
        N("zhang_wen", "张温", "司空", 3, 140, 51, "清流派", 50, 45, 28, 650, 42, 58, 72, 66, 48,
            new() { TraitNames.ShanChangMinZheng, TraitNames.LaoMouShenSuan, TraitNames.ChuShenMingMen }, "审慎", "和议用兵", "洛阳朝堂", "开局", "三公重臣，曾总督凉州军务，政略可用但容易被边军牵制"),
        N("cui_lie", "崔烈", "司徒", 3, 130, 62, "清流派", 36, 48, 72, 3200, 12, 28, 64, 58, 52,
            new() { TraitNames.MenFaShiJia, TraitNames.TanDeWuYan, TraitNames.YouXieShouZang }, "贪荣畏议", "鬻官自保", "洛阳朝堂", "开局", "名门高官而以买官受讥，适合作为清流名望与卖官腐败的矛盾样本"),
        N("qiao_xuan", "桥玄", "太尉", 4, 110, 74, "清流派", 62, 42, 5, 180, 20, 38, 76, 78, 18,
            new() { TraitNames.GangZhiBuE, TraitNames.QingZhengLianJie, TraitNames.ShanChangMinZheng, TraitNames.ShuoHuaZhiLv }, "刚正老臣", "直言举贤", "洛阳朝堂", "开局", "清望极高的老臣，曾赏识曹操；年迈可为朝廷名义与清议压舱石"),
        N("xun_shuang", "荀爽", "郎中", 2, 128, 62, "清流派", 55, 20, 3, 90, 5, 18, 84, 82, 16,
            new() { TraitNames.QingZhengLianJie, TraitNames.ShanChangMinZheng, TraitNames.XiHaoQingTan, TraitNames.QinMinWenHe }, "儒雅持正", "经学清议", "洛阳朝堂", "开局", "颍川荀氏名儒，清流舆论与士人征辟网络的代表"),
        N("chen_song", "陈嵩", "尚书", 2, 138, 58, "清流派", 48, 22, 10, 160, 8, 20, 68, 62, 25,
            new() { TraitNames.QingZhengLianJie, TraitNames.QinMinWenHe, TraitNames.ShanChangMinZheng }, "谨慎", "文书政务", "洛阳朝堂", "开局", "尚书台文吏型官员，用于补足朝廷日常政务与奏折流转"),
        N("xia_yun", "夏恽", "中常侍", 2, 138, 52, "阉党派", 64, 42, 76, 2100, 8, 10, 44, 52, 70,
            new() { TraitNames.TanDeWuYan, TraitNames.HuiPaiMaPi, TraitNames.YouXieXinJi }, "佞巧", "宫中结党", "洛阳宫中", "开局", "十常侍成员，内廷卖官与传诏网络的节点"),
        N("guo_sheng", "郭胜", "中常侍", 2, 140, 50, "阉党派", 60, 40, 74, 1900, 6, 9, 42, 56, 68,
            new() { TraitNames.TanDeWuYan, TraitNames.HuiPaiMaPi, TraitNames.ChanMeiZhuanQuan }, "机巧", "内廷护党", "洛阳宫中", "开局", "十常侍成员，依附张让赵忠，能强化阉党人数压力"),
        N("song_dian", "宋典", "中常侍", 2, 142, 51, "阉党派", 58, 34, 70, 1500, 5, 8, 38, 50, 62,
            new() { TraitNames.HuiPaiMaPi, TraitNames.YouXieShouZang, TraitNames.PuZhangLangFei }, "随势", "营私传诏", "洛阳宫中", "开局", "十常侍成员，适合作为低一档但可抄没的内廷贪宦"),
        N("han_kui", "韩悝", "中常侍", 2, 141, 50, "阉党派", 57, 32, 68, 1300, 6, 8, 36, 48, 60,
            new() { TraitNames.HuiPaiMaPi, TraitNames.YouXieXinJi, TraitNames.YouXieShouZang }, "阴柔", "宫省耳目", "洛阳宫中", "开局", "十常侍成员，宫省耳目与小规模反噬来源"),

        // 地方 / 冷备 / 事件触发
        N("dong_zhuo", "董卓", "并州刺史/河东太守", 3, 139, 53, "割据军阀", 25, 35, 70, 900, 86, 78, 42, 52, 96,
            new() { TraitNames.KongWuYouLi, TraitNames.YongBingZiZhong, TraitNames.ShouXiaYouBing, TraitNames.TanDeWuYan }, "残暴豪强", "拥兵自重", "并州边军", "事件触发", "凉州军阀，召外兵入京的灾难性风险源"),
        N("ding_yuan", "丁原", "并州刺史", 3, 140, 50, "地方州牧", 45, 32, 25, 350, 62, 68, 36, 45, 58,
            new() { TraitNames.ShouXiaYouBing, TraitNames.DongDianBingFa, TraitNames.YouXieLiQi }, "粗直", "边军自守", "并州边军", "事件触发", "并州刺史，吕布上官，非董卓的边军选择"),
        N("lu_bu", "吕布", "并州骑将", 1, 156, 43, "割据军阀", 35, 18, 35, 200, 98, 72, 18, 60, 82,
            new() { TraitNames.KongWuYouLi, TraitNames.YouXieLiQi, TraitNames.ShouXiaYouBing }, "骁勇躁动", "逐利易主", "并州边军", "事件触发", "汉末猛将，最高武力与极高易主风险并存"),
        N("liu_yan", "刘焉", "宗正", 3, 140, 54, "地方州牧", 42, 34, 28, 500, 20, 50, 78, 70, 78,
            new() { TraitNames.LaoMouShenSuan, TraitNames.ShanChangMinZheng, TraitNames.ChuShenMingMen }, "深谋自保", "外镇自立", "洛阳朝堂", "事件触发", "汉室宗亲，州牧制度与益州割据种子"),
        N("liu_yu", "刘虞", "幽州刺史", 3, 140, 53, "地方州牧", 58, 30, 5, 120, 18, 48, 82, 84, 16,
            new() { TraitNames.AiMinRuZi, TraitNames.QinMinWenHe, TraitNames.QingZhengLianJie, TraitNames.ShanChangMinZheng }, "宽厚", "怀柔安边", "幽州", "事件触发", "汉室宗亲，幽州牧，仁政安边代表"),
        N("liu_biao", "刘表", "北军中候", 2, 142, 66, "清流派", 50, 24, 20, 300, 20, 58, 78, 80, 55,
            new() { TraitNames.ShanChangMinZheng, TraitNames.ChuShenMingMen, TraitNames.XiHaoQingTan }, "儒雅守成", "联合士族", "荆州候任", "事件触发", "八俊之一，未来荆州牧，能稳地方但易形成温和割据"),
        N("tao_qian", "陶谦", "议郎", 2, 132, 62, "地方州牧", 48, 25, 32, 400, 30, 54, 58, 62, 42,
            new() { TraitNames.QinMinWenHe, TraitNames.YouXieShouZang }, "守成", "地方自保", "地方州郡", "冷备", "徐州牧，地方守成官僚"),
        N("kong_rong", "孔融", "侍御史", 1, 153, 55, "清流派", 46, 20, 3, 80, 8, 28, 60, 86, 22,
            new() { TraitNames.XiHaoQingTan, TraitNames.QingZhengLianJie, TraitNames.ShuoHuaZhiLv, TraitNames.ChuShenMingMen }, "傲直", "清议讥弹", "在野名士", "事件触发", "孔子后裔，名士清议代表"),
        N("gongsun_zan", "公孙瓒", "骑都尉", 2, 153, 46, "割据军阀", 40, 24, 30, 300, 82, 74, 30, 56, 68,
            new() { TraitNames.KongWuYouLi, TraitNames.DongDianBingFa, TraitNames.ShouXiaYouBing }, "刚烈", "强硬安边", "幽州边地", "事件触发", "幽州边将，白马义从首领"),
        N("sun_jian", "孙坚", "佐军司马", 2, 155, 37, "割据军阀", 52, 18, 18, 180, 90, 82, 36, 66, 70,
            new() { TraitNames.KongWuYouLi, TraitNames.ZhiJunYanZheng, TraitNames.GangZhiBuE }, "勇烈", "先登破敌", "地方军官", "事件触发", "江东猛将，平乱王牌与孙氏势力种子"),
        N("liu_bei", "刘备", "涿郡义兵", 0, 161, 62, "在野名士", 50, 5, 2, 20, 60, 72, 66, 92, 78,
            new() { TraitNames.AiMinRuZi, TraitNames.QinMinWenHe, TraitNames.JingTianWeiDi }, "宽厚坚忍", "仁义聚众", "涿郡在野", "黄巾触发", "汉室宗亲后裔，黄巾义兵与蜀汉源流"),
        N("guan_yu", "关羽", "在野义士", 0, 160, 60, "在野名士", 45, 3, 0, 10, 96, 84, 35, 75, 38,
            new() { TraitNames.KongWuYouLi, TraitNames.ZhiJunYanZheng, TraitNames.GangZhiBuE, TraitNames.AiBingRuZi }, "傲岸重义", "义不负主", "涿郡义兵", "刘备触发", "刘备核心将领，万人敌与忠义象征"),
        N("zhang_fei", "张飞", "在野义士", 0, 160, 61, "在野名士", 42, 3, 8, 15, 94, 78, 20, 62, 45,
            new() { TraitNames.KongWuYouLi, TraitNames.YouXieLiQi, TraitNames.AiBingRuZi }, "豪烈", "猛攻震慑", "涿郡义兵", "刘备触发", "刘备核心将领，万人敌，勇猛而性急"),
        N("xun_yu", "荀彧", "颍川孝廉", 0, 163, 50, "清流派", 48, 5, 0, 50, 10, 35, 96, 88, 35,
            new() { TraitNames.JingTianWeiDi, TraitNames.ShanChangMinZheng, TraitNames.QingZhengLianJie, TraitNames.LaoMouShenSuan }, "温雅深谋", "王佐匡汉", "颍川在野", "年月触发", "王佐之才，后期顶级政略人才"),
        N("xun_you", "荀攸", "黄门侍郎候补", 1, 157, 57, "清流派", 50, 12, 2, 70, 18, 45, 88, 70, 32,
            new() { TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi, TraitNames.QingZhengLianJie }, "沉密", "奇策制敌", "颍川士人", "事件触发", "曹操谋主之一，长于军谋与密策"),
        N("guo_jia", "郭嘉", "颍川少年名士", 0, 170, 38, "在野名士", 45, 2, 0, 30, 6, 28, 90, 78, 42,
            new() { TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi, TraitNames.XiHaoQingTan }, "放达敏锐", "奇谋短命", "颍川在野", "年月触发", "颍川后起谋士，才略极高但年少且寿短，不宜开局显达"),
        N("cheng_yu", "程昱", "东阿乡里名士", 1, 141, 80, "在野名士", 42, 3, 8, 50, 36, 50, 86, 62, 48,
            new() { TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi, TraitNames.ShanChangMinZheng }, "坚忍狠辣", "权变济世", "兖州东阿", "事件触发", "兖州谋士，擅长危局筹粮与权变，但手段会损民心清议"),
        N("tian_feng", "田丰", "冀州名士", 1, 150, 50, "在野名士", 50, 4, 2, 60, 12, 35, 84, 58, 28,
            new() { TraitNames.GangZhiBuE, TraitNames.QingZhengLianJie, TraitNames.ShuoHuaZhiLv }, "刚直急切", "逆耳谏言", "冀州在野", "事件触发", "河北名士，忠言可救国也易触怒权臣与主上"),
        N("ju_shou", "沮授", "冀州从事候补", 1, 150, 50, "在野名士", 50, 4, 3, 70, 18, 55, 88, 64, 32,
            new() { TraitNames.JingTianWeiDi, TraitNames.ShanChangMinZheng, TraitNames.LaoMouShenSuan }, "沉稳远略", "规划州郡", "冀州在野", "事件触发", "河北战略家，擅长州郡统合；若被袁氏招揽会强化河北割据"),
        N("zhang_he", "张郃", "河间郡兵", 0, 167, 64, "地方州牧", 42, 2, 5, 30, 82, 86, 48, 58, 48,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.DongDianBingFa, TraitNames.AiBingRuZi }, "机变稳健", "临阵善变", "冀州河间", "年月触发", "河北青年名将，适合后期平叛与正规军建设"),
        N("zhao_yun", "赵云", "常山义从", 0, 168, 61, "在野名士", 48, 2, 1, 20, 92, 82, 50, 76, 25,
            new() { TraitNames.KongWuYouLi, TraitNames.ZhiJunYanZheng, TraitNames.GangZhiBuE, TraitNames.AiBingRuZi }, "忠谨勇毅", "护主安民", "常山在野", "年月触发", "常山青年武人，演义名将色彩强；低野心高忠义但登场不宜过早"),
        N("tai_shi_ci", "太史慈", "东莱郡吏", 0, 166, 40, "在野名士", 46, 2, 3, 25, 90, 76, 42, 72, 38,
            new() { TraitNames.KongWuYouLi, TraitNames.GangZhiBuE, TraitNames.YouXieLiQi }, "刚烈重信", "赴义报恩", "青州东莱", "年月触发", "东莱义士，后期青徐方向武臣与名士叙事资源"),
        N("yu_jin", "于禁", "泰山郡兵", 0, 159, 62, "地方州牧", 40, 2, 6, 20, 72, 84, 44, 42, 34,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.DongDianBingFa }, "严整", "军法峻切", "兖州泰山", "年月触发", "兖州青年军官，纪律型平叛将领，魅力较低但统军可靠"),
        N("jia_xu", "贾诩", "凉州郡吏", 1, 147, 76, "割据军阀", 30, 10, 18, 100, 8, 38, 92, 55, 40,
            new() { TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi }, "冷静诡谲", "趋利避祸", "凉州", "董卓触发", "凉州谋士，善自保与奇谋"),
        N("zhang_liao", "张辽", "并州小校", 0, 169, 53, "地方州牧", 45, 2, 5, 20, 86, 88, 42, 68, 45,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.DongDianBingFa, TraitNames.AiBingRuZi }, "沉勇", "严整突击", "并州边军", "年月触发", "并州青年名将，后期平叛王牌"),
        N("han_fu", "韩馥", "御史中丞", 2, 145, 46, "地方州牧", 50, 20, 22, 250, 20, 42, 55, 45, 35,
            new() { TraitNames.CaiShuXueQian, TraitNames.QinMinWenHe }, "懦弱多疑", "守土无断", "冀州候任", "事件触发", "未来冀州牧，易受袁绍渗透"),
        N("qiao_mao", "桥瑁", "东郡太守", 2, 150, 40, "地方州牧", 48, 24, 24, 260, 38, 52, 56, 60, 50,
            new() { TraitNames.ChuShenMingMen, TraitNames.QinMinWenHe, TraitNames.YouXieLiQi }, "激烈好名", "檄文倡义", "兖州东郡", "事件触发", "东郡太守，讨董檄文传统人物，能鼓动州郡联盟也会放大地方自主"),
        N("zhang_miao", "张邈", "陈留太守", 2, 150, 45, "地方州牧", 52, 28, 18, 320, 32, 55, 62, 72, 58,
            new() { TraitNames.ChuShenMingMen, TraitNames.QinMinWenHe, TraitNames.MenFaShiJia }, "任侠好士", "宾客结交", "兖州陈留", "事件触发", "陈留名士太守，善结交诸侯，稳定地方同时埋下反复风险"),
        N("bao_xin", "鲍信", "济北相", 2, 152, 40, "地方州牧", 58, 22, 8, 180, 62, 70, 52, 64, 35,
            new() { TraitNames.ZhiJunYanZheng, TraitNames.GangZhiBuE, TraitNames.AiBingRuZi }, "忠烈", "急难赴义", "兖州济北", "事件触发", "济北相，讨董与兖州军政人物，可靠但容易战死"),
        N("kong_zhou", "孔伷", "豫州刺史", 2, 145, 45, "地方州牧", 46, 20, 20, 220, 24, 44, 58, 55, 38,
            new() { TraitNames.QinMinWenHe, TraitNames.XiHaoQingTan }, "虚名", "文士领州", "豫州", "事件触发", "豫州刺史，讨董联盟成员，名望可用但军政能力平平"),
        N("zhang_zi", "张咨", "南阳太守", 2, 145, 48, "地方州牧", 34, 25, 55, 900, 28, 42, 48, 45, 52,
            new() { TraitNames.YouXieShouZang, TraitNames.TanDeWuYan, TraitNames.CaiShuXueQian }, "苛刻", "守财拒军", "荆州南阳", "事件触发", "南阳太守，富郡官僚与军阀索粮冲突的典型触发点"),
        N("wang_rui", "王叡", "荆州刺史", 2, 145, 45, "地方州牧", 42, 28, 30, 420, 30, 50, 54, 52, 45,
            new() { TraitNames.ChuShenMingMen, TraitNames.YouXieShouZang }, "轻躁", "州郡掣肘", "荆州", "事件触发", "荆州刺史，南方州郡内斗与孙坚路线的冲突节点"),
        N("liu_dai", "刘岱", "侍中", 2, 150, 42, "地方州牧", 50, 18, 18, 200, 30, 48, 56, 62, 48,
            new() { TraitNames.ChuShenMingMen, TraitNames.QinMinWenHe }, "持名", "宗室外任", "洛阳朝堂", "事件触发", "汉室宗亲，未来兖州刺史，可作为宗室地方治理候选"),
        N("gongsun_du", "公孙度", "辽东属吏", 1, 150, 54, "割据军阀", 38, 12, 32, 260, 48, 64, 50, 46, 82,
            new() { TraitNames.LaoMouShenSuan, TraitNames.ShouXiaYouBing, TraitNames.YouXieXinJi }, "阴鸷坚忍", "边郡自立", "辽东", "事件触发", "辽东割据种子，外放可稳边但极易形成远东独立王国"),
        N("zhang_yang", "张杨", "并州从事", 1, 155, 43, "地方州牧", 45, 12, 20, 150, 58, 62, 42, 50, 52,
            new() { TraitNames.DongDianBingFa, TraitNames.ShouXiaYouBing, TraitNames.TiXuShiZu }, "质朴", "边军协从", "并州边军", "事件触发", "并州军人，能补充北地将领层次，风险低于吕布董卓"),
        N("zhang_xiu", "张绣", "凉州少年武吏", 0, 160, 50, "割据军阀", 35, 5, 12, 60, 78, 70, 36, 52, 62,
            new() { TraitNames.KongWuYouLi, TraitNames.DongDianBingFa, TraitNames.ShouXiaYouBing }, "勇悍", "从叔随军", "凉州", "年月触发", "张济从子，凉州青年将领，后期可成为西北军事变量"),
        N("zhang_ji", "张济", "凉州军司马", 1, 145, 49, "割据军阀", 30, 16, 34, 220, 66, 68, 38, 44, 70,
            new() { TraitNames.KongWuYouLi, TraitNames.ShouXiaYouBing, TraitNames.YouXieShouZang }, "悍直", "凉州逐利", "凉州", "事件触发", "凉州军人，董卓体系外延，带来军力也带来抢掠风险"),
        N("li_jue", "李傕", "凉州部曲将", 0, 150, 45, "割据军阀", 18, 8, 58, 180, 72, 60, 24, 32, 82,
            new() { TraitNames.KongWuYouLi, TraitNames.ShouXiaYouBing, TraitNames.TanDeWuYan }, "凶悍", "纵兵劫掠", "凉州", "董卓触发", "董卓部将，长安之乱风险源，不宜直接作为普通朝臣重用"),
        N("guo_si", "郭汜", "凉州部曲将", 0, 150, 45, "割据军阀", 18, 8, 60, 170, 70, 58, 22, 30, 80,
            new() { TraitNames.KongWuYouLi, TraitNames.ShouXiaYouBing, TraitNames.TanDeWuYan }, "凶狡", "纵兵分赃", "凉州", "董卓触发", "董卓部将，与李傕并为长安军阀化灾源"),
        N("zhang_jue", "张角", "大贤良师", 0, 140, 44, "反叛势力", 0, 55, 5, 300, 25, 78, 62, 90, 95,
            new() { TraitNames.AiMinRuZi, TraitNames.QinMinWenHe, TraitNames.LaoMouShenSuan }, "狂热救世", "宗教动员", "敌对势力", "黄巾触发", "太平道首领，黄巾主线敌对人物", true),
        N("zhang_bao", "张宝", "地公将军", 0, 142, 43, "反叛势力", 0, 40, 5, 120, 38, 65, 45, 75, 88,
            new() { TraitNames.QinMinWenHe, TraitNames.YouXieXinJi }, "狂热", "黄巾副帅", "敌对势力", "黄巾触发", "张角弟，黄巾副首领", true),
        N("zhang_liang", "张梁", "人公将军", 0, 143, 42, "反叛势力", 0, 38, 8, 100, 55, 68, 38, 65, 86,
            new() { TraitNames.YouXieLiQi, TraitNames.QinMinWenHe }, "躁烈", "黄巾副帅", "敌对势力", "黄巾触发", "张角弟，黄巾副首领", true),
        N("zhang_yan", "张燕", "黑山渠帅", 0, 150, 55, "反叛势力", 0, 28, 18, 160, 72, 78, 46, 68, 76,
            new() { TraitNames.KongWuYouLi, TraitNames.DongDianBingFa, TraitNames.QinMinWenHe }, "机敏坚韧", "山地流动作战", "太行黑山", "黄巾触发", "黑山军首领，黄巾余部与河北山地长期威胁", true),
        N("zhang_niujiao", "张牛角", "黑山首领", 0, 145, 42, "反叛势力", 0, 24, 20, 100, 70, 70, 32, 58, 78,
            new() { TraitNames.KongWuYouLi, TraitNames.YouXieLiQi, TraitNames.QinMinWenHe }, "悍勇", "聚众攻城", "太行黑山", "黄巾触发", "黑山军早期首领，张燕继承其部众的叛乱节点", true),
        N("bian_zhang", "边章", "凉州叛乱首领", 1, 140, 48, "反叛势力", 0, 22, 35, 260, 58, 72, 58, 60, 86,
            new() { TraitNames.ShouXiaYouBing, TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi }, "反复", "羌胡合兵", "凉州", "边章韩遂触发", "凉州叛乱首领，西北羌胡与汉吏叛乱的政治代表", true),
        N("beigong_boyu", "北宫伯玉", "羌胡首领", 0, 145, 45, "反叛势力", 0, 18, 30, 180, 76, 74, 36, 56, 84,
            new() { TraitNames.KongWuYouLi, TraitNames.ShouXiaYouBing, TraitNames.YouXieLiQi }, "桀骜", "羌骑侵扰", "凉州羌胡", "边章韩遂触发", "凉州羌胡首领，边军压力与民族叛乱代表", true),
        N("ma_teng", "马腾", "凉州军司马", 2, 156, 56, "割据军阀", 40, 18, 28, 220, 72, 72, 38, 58, 62,
            new() { TraitNames.KongWuYouLi, TraitNames.ShouXiaYouBing }, "豪爽", "边军自立", "凉州", "事件触发", "凉州军阀，马超之父"),
        N("han_sui", "韩遂", "凉州叛军首领", 2, 145, 70, "割据军阀", 20, 25, 45, 380, 55, 70, 72, 62, 86,
            new() { TraitNames.LaoMouShenSuan, TraitNames.YouXieXinJi, TraitNames.ShouXiaYouBing }, "反复诡诈", "凉州合纵", "凉州", "事件触发", "凉州叛乱首领，边乱外交家"),
    };

    public static NpcState Clone(NpcState template) => new()
    {
        Id = template.Id,
        Name = template.Name,
        Title = template.Title,
        TitleTier = template.TitleTier,
        BirthYear = template.BirthYear,
        BaseLongevity = template.BaseLongevity,
        StashedWealth = template.StashedWealth,
        Favorability = template.Favorability,
        Power = template.Power,
        Corruption = template.Corruption,
        Traits = new List<string>(template.Traits),
        Personality = template.Personality,
        Style = template.Style,
        Faction = template.Faction,
        Health = template.Health,
        IsActive = template.IsActive,
        DeathReason = template.DeathReason,
        Martial = template.Martial,
        Leadership = template.Leadership,
        Politics = template.Politics,
        Charisma = template.Charisma,
        Ambition = template.Ambition,
        GovernedProvinceId = template.GovernedProvinceId,
        InitialLocation = template.InitialLocation,
        EntryCondition = template.EntryCondition,
        HistoricalRole = template.HistoricalRole,
        IsHostile = template.IsHostile,
        HistoricalDeathYear = template.HistoricalDeathYear,
        SourceNote = template.SourceNote,
    };

    private static NpcState N(string id, string name, string title, int tier, int birthYear, int longevity, string faction,
        int favorability, int power, int corruption, int wealth,
        int martial, int leadership, int politics, int charisma, int ambition,
        List<string> traits, string personality, string style, string location, string entryCondition, string role, bool isHostile = false)
    {
        return new NpcState
        {
            Id = id,
            Name = name,
            Title = title,
            TitleTier = tier,
            BirthYear = birthYear,
            BaseLongevity = longevity,
            Faction = faction,
            Favorability = favorability,
            Power = power,
            Corruption = corruption,
            StashedWealth = wealth,
            Martial = martial,
            Leadership = leadership,
            Politics = politics,
            Charisma = charisma,
            Ambition = ambition,
            Traits = traits,
            Personality = personality,
            Style = style,
            InitialLocation = location,
            EntryCondition = entryCondition,
            HistoricalRole = role,
            IsHostile = isHostile,
            HistoricalDeathYear = birthYear + longevity,
            SourceNote = "生卒年按常见史料或游戏估算；HistoricalDeathYear 为史实倾向参考，不强制退场。",
            IsActive = true,
            Health = 100,
        };
    }
}
